# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer

-   repo: https://github.com/psf/black
    rev: '23.3.0'
    hooks:
    -   id: black
        exclude: resources.py|settingsdialog.py

-   repo: https://github.com/pycqa/flake8
    rev: '6.0.0'
    hooks:
    -   id: flake8
        additional_dependencies:
          - flake8-bugbear
          - pep8-naming
          - flake8-builtins
          - flake8-comprehensions
          - flake8-pytest-style
          - flake8-debugger
